name: convolab
description: A Signal Processing Library for Dart
version: 0.0.1
author: Richard Griffith <scribe.griff@gmail.com>
homepage: http://www.scribegriff.com
dependencies:
  unittest:
    sdk: unittest